apiVersion: apps/v1
kind: Deployment
metadata:
  name: [deployment.name]
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pipeline
  template:
    metadata:
      labels:
        component: pipeline
    spec:
      containers:
        - name: pipeline-app
          image: [pipeline.image]
          ports:
            - containerPort: 9997